#!/usr/bin/env bash
~/Downloads/bin/protoc --go_out=./internal/proto --go-grpc_opt=paths=source_relative\
    --go-grpc_out=./internal/proto --go-grpc_opt=paths=source_relative \
    proto/user.proto

