services:
  db:
    container_name: 'users_db'
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - app-network

  users:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file:
      - ./.env
    ports:
      - '50051:50051'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./:/app

  client:
    container_name: 'app_client'
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - users
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
