services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file:
      - ./.env
    ports:
      - '50051:50051'
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
