// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/protected.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtectedService_Admin_FullMethodName = "/protected.ProtectedService/Admin"
)

// ProtectedServiceClient is the client API for ProtectedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtectedServiceClient interface {
	Admin(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*AdminResponse, error)
}

type protectedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtectedServiceClient(cc grpc.ClientConnInterface) ProtectedServiceClient {
	return &protectedServiceClient{cc}
}

func (c *protectedServiceClient) Admin(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*AdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResponse)
	err := c.cc.Invoke(ctx, ProtectedService_Admin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtectedServiceServer is the server API for ProtectedService service.
// All implementations must embed UnimplementedProtectedServiceServer
// for forward compatibility.
type ProtectedServiceServer interface {
	Admin(context.Context, *AdminRequest) (*AdminResponse, error)
	mustEmbedUnimplementedProtectedServiceServer()
}

// UnimplementedProtectedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtectedServiceServer struct{}

func (UnimplementedProtectedServiceServer) Admin(context.Context, *AdminRequest) (*AdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admin not implemented")
}
func (UnimplementedProtectedServiceServer) mustEmbedUnimplementedProtectedServiceServer() {}
func (UnimplementedProtectedServiceServer) testEmbeddedByValue()                          {}

// UnsafeProtectedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtectedServiceServer will
// result in compilation errors.
type UnsafeProtectedServiceServer interface {
	mustEmbedUnimplementedProtectedServiceServer()
}

func RegisterProtectedServiceServer(s grpc.ServiceRegistrar, srv ProtectedServiceServer) {
	// If the following call pancis, it indicates UnimplementedProtectedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtectedService_ServiceDesc, srv)
}

func _ProtectedService_Admin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtectedServiceServer).Admin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtectedService_Admin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtectedServiceServer).Admin(ctx, req.(*AdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtectedService_ServiceDesc is the grpc.ServiceDesc for ProtectedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtectedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protected.ProtectedService",
	HandlerType: (*ProtectedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Admin",
			Handler:    _ProtectedService_Admin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/protected.proto",
}
